server:
  port: 8888
spring:
  thymeleaf:
    #开发配置为false,避免修改模板还要重启服务器
    cache: false
    #配置模板路径，默认是templates，可以不用配置
    prefix: classpath:/templates/
  redis:
    host: redis
    port: 6379
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）d
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0

  datasource:
    url: jdbc:mysql://db:3306/test
    username: root
    password: root


